const defaultTheme = require("tailwindcss/defaultTheme");
const theme = require("./constants/theme");

const {
  colors: { dark, light, common },
} = theme;

module.exports = {
  mode: "jit",
  purge: ["./**/*.html", "./**/*.vue", "./**/*.jsx", "./**/*.tsx"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./lib/**/*.{js,ts,jsx,tsx}",
    "./stories/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class", // or 'media' or 'class',
  important: true,
  theme: {
    colors: {
      light: {
        primary: common.primary6,
        "primary-hover": common.primary7,
        "on-primary": common.primary10,
        "primary-container": common.primary2,
        "primary-container-hover": common.primary3,
        "on-primary-container": common.primary9,
        secondary: light.secondary,
        "secondary-hover": common.secondary9,
        "on-secondary": common.neutral1,
        "secondary-container": common.secondary3,
        "secondary-container-hover": common.secondary4,
        "on-secondary-container": common.secondary10,
        background: light.background,
        "on-background": common.neutral11,
        surface: common.neutral1,
        "on-surface": common.neutral11,
        "primary-1": common.primary1,
        "primary-2": common.primary2,
        "primary-3": common.primary3,
        "primary-4": common.primary4,
        "primary-5": common.primary5,
        "primary-6": common.primary6,
        "primary-7": common.primary7,
        "primary-8": common.primary8,
        "primary-9": common.primary9,
        "primary-10": common.primary10,
        "secondary-1": common.secondary1,
        "secondary-2": common.secondary2,
        "secondary-3": common.secondary3,
        "secondary-4": common.secondary4,
        "secondary-5": common.secondary5,
        "secondary-6": common.secondary6,
        "secondary-7": common.secondary7,
        "secondary-8": common.secondary8,
        "secondary-9": common.secondary9,
        "secondary-10": common.secondary10,
        "neutral-1": common.neutral1,
        "neutral-2": common.neutral2,
        "neutral-3": common.neutral3,
        "neutral-4": common.neutral4,
        "neutral-5": common.neutral5,
        "neutral-6": common.neutral6,
        "neutral-7": common.neutral7,
        "neutral-8": common.neutral8,
        "neutral-9": common.neutral9,
        "neutral-10": common.neutral10,
      },
      dark: {
        primary: common.primary5,
        "primary-hover": common.primary4,
        "on-primary": common.primary9,
        "primary-container": common.primary8,
        "primary-container-hover": common.primary7,
        "on-primary-container": common.primary2,
        secondary: common.secondary3,
        "secondary-hover": common.secondary2,
        "on-secondary": common.secondary9,
        "secondary-container": common.secondary8,
        "secondary-container-hover": common.secondary7,
        "on-secondary-container": common.secondary2,
        background: dark.background,
        "on-background": dark.onBackground,
        surface: dark.surface,
        "on-surface": dark.onBackground,
        "primary-1": common.primary10,
        "primary-2": common.primary9,
        "primary-3": common.primary8,
        "primary-4": common.primary7,
        "primary-5": common.primary6,
        "primary-6": common.primary5,
        "primary-7": common.primary4,
        "primary-8": common.primary3,
        "primary-9": common.primary2,
        "primary-10": common.primary1,
        "secondary-1": common.secondary10,
        "secondary-2": common.secondary9,
        "secondary-3": common.secondary8,
        "secondary-4": common.secondary7,
        "secondary-5": common.secondary6,
        "secondary-6": common.secondary5,
        "secondary-7": common.secondary4,
        "secondary-8": common.secondary3,
        "secondary-9": common.secondary2,
        "secondary-10": common.secondary1,
        "neutral-1": common.neutral12,
        "neutral-2": common.neutral11,
        "neutral-3": common.neutral10,
        "neutral-4": common.neutral9,
        "neutral-5": common.neutral8,
        "neutral-6": common.neutral7,
        "neutral-7": common.neutral6,
        "neutral-8": common.neutral5,
        "neutral-9": common.neutral4,
        "neutral-10": common.neutral3,
        "neutral-11": common.neutral2,
        "neutral-12": common.neutral1,
      },
      common: {
        success: common.success,
        "success-hover": common.successHover,
        info: common.info,
        "info-hover": common.infoHover,
        warning: common.warning,
        "yellow-hover": common.yellowHover,
        error: common.error,
        "error-hover": common.errorHover,
        black: common.black,
        "neutral-center": common.neutralCenter,
        white: common.white,
      },
    },
    fontSize: {
      ...defaultTheme.fontSize,
      xxs: ".65rem",
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
};